---
abstract: 'remove duplicated item from array'
author:
  - 'Yasuhiro Matsumoto <mattn.jp@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  Module::Build::Tiny: 0
dynamic_config: 0
generated_by: 'Minilla/v0.0.49, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Deduper
provides:
  Data::Deduper:
    file: lib/Data/Deduper.pm
    version: 0.03
requires:
  Filter::Util::Call: 0
resources:
  bugtracker: https://github.com/mattn/p5-Data-Deduper/issues
  homepage: https://github.com/mattn/p5-Data-Deduper
  repository: https://github.com/mattn/p5-Data-Deduper
version: 0.03
